//*** analog_network.pb ***
//* This file is automatically generated.
//* (c) Copyright 2007-2009 Cadence Design Systems, Inc.
//* All rights reserved.
//*
//* Portbind file for:
//* SPICE subckt ANALOG_NETWORK : HDL module ANALOG_NETWORK
//* SPICE port	:	HDL port	:	HDL Parameters

// Bus definition. Note that bus delimiters in spice are <>, whilst in verilog []. Hence the 'special' statement
in_analog	:	IN_DIGITAL	:	dir=input
out_analog	:	OUT_DIGITAL	:	dir=output
