//*** analog_network.pb ***
//* This file is automatically generated.
//* (c) Copyright 2007-2009 Cadence Design Systems, Inc.
//* All rights reserved.
//*
//* Portbind file for:
//* SPICE subckt ANALOG_NETWORK : HDL module ANALOG_NETWORK
//* SPICE port	:	HDL port	:	HDL Parameters

// Bus definition. Note that bus delimiters in spice are <>, whilst in verilog []. Hence the 'special' statement
G1	:	SWIPT_OUT0	:	dir=input
G2	:	SWIPT_OUT1	:	dir=input
G3	:	SWIPT_OUT2	:	dir=input
G4	:	SWIPT_OUT3	:	dir=input
acout0	:	ACOUT0	:	dir=output
acout1	:	ACOUT1	:	dir=output
acout2	:	ACOUT2	:	dir=output
acout3	:	ACOUT3	:	dir=output
acout4	:	ACOUT4	:	dir=output
acout5	:	ACOUT5	:	dir=output
acout6	:	ACOUT6	:	dir=output
acout7	:	ACOUT7	:	dir=output
acout8	:	ACOUT8	:	dir=output
acout9	:	ACOUT9	:	dir=output
acout10	:	ACOUT10	:	dir=output
acout11	:	ACOUT11	:	dir=output
