//*** analog_network.pb ***
//* This file is automatically generated.
//* (c) Copyright 2007-2009 Cadence Design Systems, Inc.
//* All rights reserved.
//*
//* Portbind file for:
//* SPICE subckt ANALOG_NETWORK : HDL module ANALOG_NETWORK
//* SPICE port	:	HDL port	:	HDL Parameters

// Bus definition. Note that bus delimiters in spice are <>, whilst in verilog []. Hence the 'special' statement
G1	:	SWIPT_OUT0	:	dir=input
G2	:	SWIPT_OUT1	:	dir=input
G3	:	SWIPT_OUT2	:	dir=input
G4	:	SWIPT_OUT3	:	dir=input
